config/routes.rb
Cove::Application.routes.draw do
  resources :videos
  
  match 'videos/:video_id/tag', :to => 'videos#tag'

  resources :tags

  resources :jobs

  resources :trainings

  match 'jobs/:id/work' => 'jobs#work'

  resource :logging

  get '/search' => "search#show", :as => "search"

  devise_for :users

  root :to => "home#index"

  resources :videos

  match 'certifications/:id/take_test', :to => 'certifications#take_test', :as => 'take_test'

  match 'certification_tests/:id', :to => 'certification_tests#show', :as => 'show_test'
  match 'certification_tests/:id/test_results', :to => 'certification_tests#test_results', :as => 'test_results'
  match 'certification_tests/:id/submit_test', :to => 'certification_tests#submit_test', :as => 'submit_test'
  match 'certification_tests/:id/tag', :to => 'certification_tests#tag', :as => 'post_certification_test_tag'

  match 'certification_videos/:id/seed', :to => 'certification_videos#seed', :as => 'seed_certification_video'
  match 'certification_videos/:id/post_seed', :to => 'certification_videos#post_seed', :as => 'post_seed_certification_video'

end

app/models/training.rb
class Training < ActiveRecord::Base
	has_many :training_tags
	has_many :tags, :through => :training_tags
	has_many :training_videos
	has_many :video_trainings, :through => :training_videos

   validates :title, :presence => true,
                     :uniqueness => true, 
                     :length   => { :maximum => 50 }

   validates :description, 
                     :presence => true,
                     :length   => { :maximum => 255 }

#   validates_presence_of :tags
#   validates_presence_of :video_trainings

	def video_names 
		video_trainings.map{|v| v.name}
	end

	def tag_names
		tags.map{|t| t.name}
	end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  # GET /trainings
  # GET /trainings.xml
  def index
    @trainings = Training.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trainings }
    end
  end

  # GET /trainings/new
  # GET /trainings/new.xml
  def new
    @training = Training.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @training }
    end
  end

  # POST /trainings
  # POST /trainings.xml
  def create
    @training = Training.new(params[:training])

    @training.tag_ids = params[:unbound_tag_ids];
    @training.video_training_ids= params[:unbound_video_training_ids];

    respond_to do |format|
      if @training.save
        format.html { redirect_to(@training, :notice => 'Training module was successfully created.') }
        format.xml  { render :xml => @training, :status => :created, :location => @training }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @training.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /trainings/1
  # GET /trainings/1.xml
  def show
    @training = Training.find(params[:id])

    if params[:destroy]
      render 'confirm_destroy' and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @training }
    end
  end

  def edit
    @training = Training.find(params[:id])
  end

  def update
    @training = Training.find(params[:id])

    @training.tag_ids = params[:unbound_tag_ids];
    @training.video_training_ids= params[:unbound_video_training_ids];

    respond_to do |format|
      if @training.update_attributes(params[:training])
        format.html { redirect_to(@training, :notice => 'Training was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @training.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    TrainingVideo.where(:training_id => params[:id]).each do |training_video|
      training_video.destroy
    end

    TrainingTag.where(:training_id => params[:id]).each do |training_tag|
      training_tag.destroy
    end

    @training = Training.find(params[:id])
    @training.destroy

   redirect_to(trainings_url)
  end
end

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% @training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

	<div class="field">
		<%= f.label :tag %><br />
		<%= select_tag "unbound_tag_ids[]", 
            options_from_collection_for_select(Tag.all, "id", "name",
             @training.tags.map{|t| t.id}), :multiple => false, 
             :include_blank => "Select a tag" %>
	</div>

	<div class="field">
		<%= f.label :videos%><br />
		<%= select_tag "unbound_video_training_ids[]", 
            options_from_collection_for_select(VideoTraining.all, "id", "name", 
            @training.video_trainings.map{|v| v.id}), :multiple => false, 
            :include_blank => "Select a video" %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/delete.html.erb
<h2>Are you sure you want to delete this Training?</h2>
<% form_for @post, :html => { :method => 'delete' } do |f| %>
    <%= submit_tag "Yes" %>
    <%= submit_tag "No", :name => "cancel" %>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<h1>Listing training videos</h1>

<table border="1">
<tr>
   <td>Title</td>
   <td>Tags</td>
   <td>Videos</td>
   <td>Description</td>
	<% if current_user.kind == "admin" %>
      <td>Edit</td>
      <td>Delete</td>
   <% end %>
</tr>

	<% @trainings.each do |training| %>
      <tr>
         <td><%= training.title %></td>
         <td><%= training.tag_names.join(", ") %></td>
         <td><%= training.video_names.join(", ") %></td>
         <td><%= training.description %></td>
			<% if current_user.kind == "admin" %>
				<td><%= link_to 'Edit', edit_training_path(training) %></td>
            <td><%= link_to 'Destroy', training, :confirm => 'Are you sure?', :method => :delete %></td>
			<% end %>
      </tr>
	<% end %>

</table>

<br />

<%= link_to 'New Training Module', new_training_path %>

app/views/trainings/new.html.erb
<h1>New training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @training.title %>
</p>

<p>
  <b>Description:</b>
  <%= @training.description %>
</p>

<p>
  <b>Video:</b>
  <%= @training.video_names %>
</p>

<p>
  <b>Tag:</b>
  <%= @training.tag_names %>
</p>


<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>