config/routes.rb
Cove::Application.routes.draw do
  resources :videos
  
  match 'videos/:video_id/tag', :to => 'videos#tag'

  resources :tags

  resources :jobs

  resources :trainings

  match 'jobs/:id/work' => 'jobs#work'

  resource :logging

  get '/search' => "search#show", :as => "search"

  devise_for :users

  root :to => "home#index"

  resources :videos

  match 'certifications/:id/take_test', :to => 'certifications#take_test', :as => 'take_test'

  match 'certification_tests/:id', :to => 'certification_tests#show', :as => 'show_test'
  match 'certification_tests/:id/test_results', :to => 'certification_tests#test_results', :as => 'test_results'
  match 'certification_tests/:id/submit_test', :to => 'certification_tests#submit_test', :as => 'submit_test'
  match 'certification_tests/:id/tag', :to => 'certification_tests#tag', :as => 'post_certification_test_tag'

  match 'certification_videos/:id/seed', :to => 'certification_videos#seed', :as => 'seed_certification_video'
  match 'certification_videos/:id/post_seed', :to => 'certification_videos#post_seed', :as => 'post_seed_certification_video'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :job_tags
	has_many :jobs, :through => :job_tags
	has_many :video_tags
	has_many :videos, :through => :video_tags
	has_one :certification
	
	before_create :build_certification
	  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_filter :require_admin
  

  # GET /tags
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { 
        case params[:commit]
           when /Save tag and Create Job/
             redirect_to(new_job_path(:tag => @tag.id), :notice => 'Tag was successfully created.') 
          when /Save tag/
             redirect_to(@tag, :notice => 'Tag was successfully created.')
        end
      }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /tags/1
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2
        = pluralize(@tag.errors.count, "error")
        prohibited this tag from being saved:

      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  %dl.none
    %dt
      = f.label :name
    %dd
      = f.text_field :name
    %dt
      = f.label :description
    %dd
      = f.text_area :description, :rows => 5, :cols => 54
    %dt
      = f.submit "Save tag", :class => "ack"
    %dt
      = f.submit "Save tag and Create Job", :class => "ack"

app/views/tags/edit.html.haml
%h2 Edit Tag

.grid_6

  = render 'form'
  = link_to 'Back to tag', @tag, :class => "link_button neg"
  = link_to 'Cancel', tags_path, :class => "link_button neg"

app/views/tags/index.html.haml
#tags_block.grid_6

  %h2 Tags


  - if @tags.length == 0
    = "There are no tags yet! Will you make the first one?"
    = link_to 'Create New Tag', new_tag_path, :class => "link_button" 
  - else
    %p
      Click on the tags to <b>edit</b> or <b>delete</b> tags. You can also <b>create jobs</b> by going to the tag page.
    - @tags.each do |tag| 
      %dl.none
        %dt
          = link_to tag.name, tag 
        %dd
          = tag.description    

- if @tags.length != 0
  #filler_tags.grid_6
    %h3 Can't find your tag?
    %p
      = "Make a new tag! But make sure your tag doesn't exist already!"
    = link_to 'Create New Tag', new_tag_path, :class => "link_button" 

app/views/tags/new.html.haml
%h2 Create a Tag

.grid_6
  = render 'form'
  = link_to 'Cancel', tags_path, :class => "link_button neg"

app/views/tags/show.html.haml
 
%dl.none
  %dt.grid_4
    = @tag.name
    %dd.grid_8.bottomSpace 
      = @tag.description
      = link_to 'Edit', edit_tag_path(@tag), :class => "link_button small"
    %dt.grid_4
      Certification Videos
    %dd.grid_8.bottomSpace
      - @tag.certification.certification_videos.each do |cv|
        %p
          = cv.video.name
          - if not cv.seeded?
            = link_to 'Unseeded. Click to seed.', seed_certification_video_path(@cv)
        
    %dt.grid_4
      Attached jobs
    %dd.grid_8.bottomSpace
      = link_to 'Make a Job', new_job_path(:tag => @tag.id), :class => "link_button small"
    
.grid_3.bottomSpace.suffix_6
  = link_to 'Back', tags_path, :class => "link_button neg"      
.grid_3
  = link_to 'Delete', @tag, :confirm => 'Are you sure?', :method => :delete, :class => "link_button neg"
      