config/routes.rb
Cove::Application.routes.draw do
  resources :videos
  
  match 'videos/:video_id/tag', :to => 'videos#tag'

  resources :tags

  resources :jobs

  resources :trainings

  match 'jobs/:id/work' => 'jobs#work'

  resource :logging

  get '/search' => "search#show", :as => "search"

  devise_for :users

  root :to => "home#index"

  resources :videos

  match 'certifications/:id/take_test', :to => 'certifications#take_test', :as => 'take_test'

  match 'certification_tests/:id', :to => 'certification_tests#show', :as => 'show_test'
  match 'certification_tests/:id/test_results', :to => 'certification_tests#test_results', :as => 'test_results'
  match 'certification_tests/:id/submit_test', :to => 'certification_tests#submit_test', :as => 'submit_test'
  match 'certification_tests/:id/tag', :to => 'certification_tests#tag', :as => 'post_certification_test_tag'

  match 'certification_videos/:id/seed', :to => 'certification_videos#seed', :as => 'seed_certification_video'
  match 'certification_videos/:id/post_seed', :to => 'certification_videos#post_seed', :as => 'post_seed_certification_video'

end

app/models/job_video.rb
class JobVideo < ActiveRecord::Base
	belongs_to :job
	belongs_to :video
end

app/helpers/job_videos_helper.rb
module JobVideosHelper
end

app/views/job_videos/_form.html.erb
<%= form_for(@job_video) do |f| %>
  <% if @job_video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_video.errors.count, "error") %> prohibited this job video from being saved:</h2>

      <ul>
      <% @job_video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_id %><br />
    <%= f.text_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :video_id %><br />
    <%= f.text_field :video_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_videos/edit.html.erb
<h1>Editing job video</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_video %> |
<%= link_to 'Back', job_videos_path %>

app/views/job_videos/index.html.erb
<h1>Listing job videos</h1>

<table>
  <tr>
    <th>Job</th>
    <th>Video</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_videos.each do |job_video| %>
  <tr>
    <td><%= job_video.job_id %></td>
    <td><%= job_video.video_id %></td>
    <td><%= link_to 'Show', job_video %></td>
    <td><%= link_to 'Edit', edit_job_video_path(jobvideo) %></td>
    <td><%= link_to 'Destroy', job_video, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jobvideo', new_job_video_path %>

app/views/job_videos/new.html.erb
<h1>New job video</h1>

<%= render 'form' %>

<%= link_to 'Back', job_videos_path %>

app/views/job_videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job:</b>
  <%= @job_video.job_id %>
</p>

<p>
  <b>Video:</b>
  <%= @job_video.video_id %>
</p>


<%= link_to 'Edit', edit_job_video_path(@job_video) %> |
<%= link_to 'Back', job_videos_path %>